#!/bin/bash

echo "Building Javo ..."
go mod download
go build -o bin/javo

if [ "$JAVO_HOME" == '' ]; then
    echo 'Cannot find JAVO_HOME, install to default location: /usr/local/javo'
    sudo mkdir -p /usr/local/javo
    sudo chown -R "${USER}" /usr/local/javo
    export JAVO_HOME=/usr/local/javo
fi

echo "Installing package to $JAVO_HOME ..."

mkdir -p $JAVO_HOME/bin
mkdir -p $JAVO_HOME/log
cp bin/* $JAVO_HOME/bin/

sudo cp -rf jdk $JAVO_HOME/

echo "Done! 🍻"

javo -cp example HelloWorld
